### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kaggypants** [wolfcomp/MonsterDex#210]
### Dalamud log

https://i.imgur.com/Mx3G7HL.jpeg

23:30:30.631 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/en/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:30.773 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/en/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.022 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/ja-JP/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.155 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/ja-JP/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.412 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/fr-FR/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.545 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/fr-FR/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.799 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/de-DE/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:31.924 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/de-DE/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:32.206 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/zh-CN/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:32.345 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/zh-CN/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:32.608 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/zh-TW/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:32.742 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/zh-TW/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:33.003 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/ko-KR/Eureka/Hyd.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131
23:30:33.149 | ERR | [DeepDungeonDex] Trying to get file from precompiled data
	System.Net.Http.HttpRequestException: Request: Localization/ko-KR/Territories.yml
	Failed with status code NotFound
	   at DeepDungeonDex.Requests.Get(String url) in /work/repo/DeepDungeonDex/Requests/Data.cs:line 131

### Steps to reprduce

1. Load into POTD
2. Target a mimic or Moldering Merchant 

### Environment

```markdown
- **OS**: Windows 11
- **Dalamud**: D10.0.0.0.13
```

### Anything else?

Your addon keeps throwing errors for certain enemies. However, the more troubling aspects are as follows:

https://www.youtube.com/watch?v=-gAQUZDwVXE

1) Anytime there is an error, your addon is causing XIV to take a performance hit. Please view the attached video for an example. You can see when I target the Moldering Merchant (@0:23) that my FPS in the upper right is cut in two from 117 to 75 to 58~60.

2) Additionally, whenever this happens your floor guide overlay is becoming distorted/enlarged and flashing across the screen several times. This is being recorded by Shadowplay.  I would also guess this is the cause of the performance hit.

**Comment by wolfcomp** [comment]
Find relevant stack trace until then it is impossible for me to trace.
